[build]
  publish = "public"

[functions]
  directory = "server"

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/data"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/index"
  status = 200